from __future__ import annotations

import sys
from dataclasses import dataclass
from types import ModuleType


def _install_lancedb_embedding_stubs() -> None:
    """Avoid importing LanceDB's optional embedding/reranker plugins.

    CogniOS stores vectors generated by its own embedder and does not use
    LanceDB's provider registry. LanceDB still imports the registry package at
    module import time; the real package eagerly imports optional providers
    such as transformers, torch, and cloud SDKs. The frozen sidecar keeps a
    minimal registry surface so table metadata parsing works without dragging
    those optional runtimes into the app bundle.
    """

    if "lancedb.embeddings" in sys.modules:
        return

    @dataclass
    class EmbeddingFunctionConfig:
        source_column: str
        vector_column: str
        function: object

    class EmbeddingFunctionRegistry:
        @classmethod
        def get_instance(cls):
            return _REGISTRY

        def __init__(self) -> None:
            self._variables: dict[str, str] = {}

        def register(self, alias: str | None = None):
            def decorator(cls):
                return cls

            return decorator

        def parse_functions(self, metadata):
            return {}

        def get_table_metadata(self, func_list):
            return None

        def set_var(self, name: str, value: str) -> None:
            self._variables[name] = value

        def get_var(self, name: str) -> str:
            return self._variables[name]

    _REGISTRY = EmbeddingFunctionRegistry()

    embeddings = ModuleType("lancedb.embeddings")
    embeddings.EmbeddingFunctionConfig = EmbeddingFunctionConfig
    embeddings.EmbeddingFunctionRegistry = EmbeddingFunctionRegistry
    embeddings.get_registry = EmbeddingFunctionRegistry.get_instance
    embeddings.register = _REGISTRY.register

    registry = ModuleType("lancedb.embeddings.registry")
    registry.EmbeddingFunctionRegistry = EmbeddingFunctionRegistry
    registry.get_registry = EmbeddingFunctionRegistry.get_instance
    registry.register = _REGISTRY.register

    rerankers = ModuleType("lancedb.rerankers")
    rerankers.__path__ = []

    reranker_base = ModuleType("lancedb.rerankers.base")

    class Reranker:
        def __init__(self, *args, **kwargs) -> None:
            pass

    reranker_base.Reranker = Reranker

    reranker_rrf = ModuleType("lancedb.rerankers.rrf")

    class RRFReranker(Reranker):
        pass

    reranker_rrf.RRFReranker = RRFReranker

    reranker_util = ModuleType("lancedb.rerankers.util")

    def check_reranker_result(*args, **kwargs):
        return None

    reranker_util.check_reranker_result = check_reranker_result
    rerankers.Reranker = Reranker
    rerankers.RRFReranker = RRFReranker

    sys.modules["lancedb.embeddings"] = embeddings
    sys.modules["lancedb.embeddings.registry"] = registry
    sys.modules["lancedb.rerankers"] = rerankers
    sys.modules["lancedb.rerankers.base"] = reranker_base
    sys.modules["lancedb.rerankers.rrf"] = reranker_rrf
    sys.modules["lancedb.rerankers.util"] = reranker_util


_install_lancedb_embedding_stubs()

from search_sidecar.__main__ import main


if __name__ == "__main__":
    sys.exit(main())
