import {
  createFolder,
  createMount,
  createNote,
  createUrl,
  deleteNode,
  getExplorerSnapshot,
  getNodeStatusSnapshot,
  getMountSetupContext,
  getNodeThumbnail,
  getNoteContent,
  readFileContent,
  reindexNode,
  renameNode,
  retryUrl,
  saveNoteContent,
  showNodeExtractArtifacts,
  showNodeInFileManager,
} from "../../../lib/tauri/ipc";
import type { ExplorerClient } from "../types/explorer";

export const explorerClient: ExplorerClient = {
  getExplorerSnapshot,
  getNodeStatusSnapshot,
  getMountSetupContext,
  createFolder,
  createMount,
  createNote,
  createUrl,
  renameNode,
  deleteNode,
  reindexNode,
  retryUrl,
  getNodeThumbnail,
  getNoteContent,
  saveNoteContent,
  readFileContent,
  showNodeInFileManager,
  showNodeExtractArtifacts,
};
